import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import {
  initMultilocale,
  useTranslation,
} from '@multilocale/multilocale-react/index.js'
import MultilocaleProvider from '@multilocale/multilocale-react/MultilocaleProvider.js'
import styles from '../styles/Home.module.css'

initMultilocale({
  organizationId: 'e395dba6a14d8af4c2d35890',
  project: 'multilocale-nextjs-example',
})

export default function Home() {
  const { locale } = useRouter()
  const { t } = useTranslation(locale)

  return (
    <MultilocaleProvider>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1
            className={styles.title}
            dangerouslySetInnerHTML={{
              __html: t('Welcome to Next.js!'),
            }}
          />
          <h3>
            <a href="/en">English</a> &nbsp;&nbsp;&nbsp;
            <a href="/es">Español</a>
          </h3>
          <p
            className={styles.description}
            dangerouslySetInnerHTML={{
              __html: t('Get started by editing {pages/index.js}').replace(
                '{pages/index.js}',
                '<code className={styles.code}>pages/index.js</code>',
              ),
            }}
          />

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>{t('Documentation')} &rarr;</h2>
              <p>
                {t(
                  'home.documentation.description',
                  'Find in-depth information about Next.js features and API.',
                )}
              </p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>{t('Learn')} &rarr;</h2>
              <p>
                {t(
                  'home.learn.description',
                  'Learn about Next.js in an interactive course with quizzes!',
                )}
              </p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>{t('Examples')} &rarr;</h2>
              <p>
                {t(
                  'home.examples.description',
                  'Discover and deploy boilerplate example Next.js projects.',
                )}
              </p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.card}
            >
              <h2>{t('Deploy')} &rarr;</h2>
              <p>
                {t(
                  'home.deploy.description',
                  'Instantly deploy your Next.js site to a public URL with Vercel.',
                )}
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </MultilocaleProvider>
  )
}
